export class AdventureMessage {
  type: AdventureMessageType
  message: any;
}

export enum AdventureMessageType {
  UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN',
  UPDATE_CHARACTER = 'UPDATE_CHARACTER',
  UPDATE_MONSTER = 'UPDATE_MONSTER',
  ROLL_INITIATIVE = 'ROLL_INITIATIVE',
  GOTO = 'GOTO',
  MOUSE_MOVE = 'MOUSE_MOVE',
  ADD_LAYER_ITEM = 'ADD_LAYER_ITEM',
  UPDATE_LAYER_ITEM = 'UPDATE_LAYER_ITEM',
  REMOVE_LAYER_ITEM = 'REMOVE_LAYER_ITEM',
  SELECT_MONSTER = 'SELECT_MONSTER',
  ALERT = 'ALERT',
  SOUND = 'SOUND',
  AMBIENT_SOUND = 'AMBIENT_SOUND',
  CLOSE_DIALOG = 'CLOSE_DIALOG',
  ASK_NEXT_TURN = 'ASK_NEXT_TURN',
  VALIDATE_NEXT_TURN = 'VALIDATE_NEXT_TURN',
  ASK_TRADE = 'ASK_TRADE',
  SELECT_TRADE_CARD = 'SELECT_TRADE_CARD',
  ASK_SWITCH = 'ASK_SWITCH',
  SELECT_SWITCH_CARD = 'SELECT_SWITCH_CARD',
  ADD_LOG = 'ADD_LOG',
}

export class MouseMove {
  userId: number;
  username: string;
  x: number;
  y: number;
  offsetX: number;
  offsetY: number;
}
